spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: organization
          uri: lb://ORGANIZATION
          predicates:
            - Path=/organization/**
        - id: license
          uri: lb://LICENSE
          predicates:
            - Path=/v1/organizations/*/licenses/*

server:
  port: 5555
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
